# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-10-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
            - venv-10-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - venv-10-{{ .Branch }}
            - venv-10

      - run:
          name: Install dependencies
          command: |
            git submodule sync
            git submodule update --init
            pip install -U pip flake8
            pip -V
            pip install -U -r requirements.txt
            pip install coverage coveralls

            # google-cloud-sdk: https://cloud.google.com/sdk/docs/install#deb
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates gnupg google-cloud-sdk google-cloud-cli-firestore-emulator openjdk-21-jre-headless pkg-config

      - run:
          name: Run tests
          command: |
            gcloud emulators firestore start --host-port=:8089 --database-mode=datastore-mode < /dev/null >& /tmp/firestore-emulator.log &
            sleep 5s
            python3 -m coverage run --include=oauth_dropins/webutil/handlers.py,oauth_dropins/webutil/models.py,oauth_dropins/webutil/util.py -m unittest discover -v -p 'test_*.py'
            kill %1
            python3 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then python3 -m coveralls || true; fi

            # check for unintentionally overridden test methods
            # https://flake8.pycqa.org/en/latest/user/error-codes.html#error-codes
            # https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-select
            python3 -m flake8 --select=F811 oauth_dropins/webutil/tests/test_*.py

      - save_cache:
          key: venv-10-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/.pyenv
            # Ideally we'd cache these, but they need root, and the cimg/python
            # Docker image's default user is circleci :/
            # https://github.com/cypress-io/circleci-orb/issues/269
            #
            # - /usr/lib/google-cloud-sdk
            # - /usr/lib/jvm/java-21-openjdk-amd64

      - store_artifacts:
          path: /tmp/coverage_html
