# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      # https://hub.docker.com/r/google/cloud-sdk
      - image: google/cloud-sdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-9-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
            - venv-9-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - venv-9-{{ .Branch }}
            - venv-9

      - run:
          name: Install dependencies
          command: |
            git submodule sync
            git submodule update --init
            apt-get -y install virtualenv
            virtualenv local
            source local/bin/activate
            pip install -U pip flake8
            pip -V
            pip install -U -r requirements.txt
            pip install coverage coveralls

            apt-get install google-cloud-cli-firestore-emulator

      - run:
          name: Run tests
          command: |
            source local/bin/activate
            gcloud emulators firestore start --host-port=:8089 --database-mode=datastore-mode < /dev/null >& /tmp/firestore-emulator.log &
            sleep 5s
            python3 -m coverage run --include=oauth_dropins/webutil/handlers.py,oauth_dropins/webutil/models.py,oauth_dropins/webutil/util.py -m unittest discover -v -p 'test_*.py'
            kill %1
            python3 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then python3 -m coveralls || true; fi

            # check for unintentionally overridden test methods
            # https://flake8.pycqa.org/en/latest/user/error-codes.html#error-codes
            # https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-select
            flake8 --select=F811 oauth_dropins/webutil/tests/test_*.py

      - save_cache:
          key: venv-9-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - "/root/project/local/lib/python3.11/site-packages/"

      - store_artifacts:
          path: /tmp/coverage_html
